### ISSUE TITLE
How to use with form actions in SvelteKit?

### ISSUE THREAD

**Issue by leonardodipace** [harryhdt/svelte-simple-form#1]
### Problem
When attempting to combine svelte-simple-form with SvelteKit's form actions, the server-side action never gets called.

### Reproduction
```svelte
<script lang="ts">
  // +page.svelte
  import { z } from "zod"
  import { useForm } from "svelte-simple-form"
  
  type FormType = z.infer<typeof schema>

  const schema = z.object({
    email: z.string().email(),
    password: z.string(),
  })
  
  const { form, enhance } = useForm<FormType>({
    schema: schema,
    initialValue: {
      email: "",
      password: "",
    },
  })
</script>

<form method="post" use:enhance>
  <input type="email" name="email" bind:value={form.data.email} />
  <input type="password" name="password" bind:value={form.data.password} />
  <button type="submit">Submit</button>
</form>
```

```typescript
// +page.server.ts
export const actions = {
  default: async (event) => {
    const formData = await event.request.formData()
    console.log(formData)
  },
}
```

### Expected Behavior
- Form submission should trigger the server-side action
- Form data should be accessible in the action handler

### Actual Behavior
- Server-side action is never called when form is submitted
- No errors are shown in the console

### Questions
1. Is there a way to properly integrate svelte-simple-form with SvelteKit's form actions?
2. Are there any additional configuration steps needed?

PS: I love this library, keep it up!

**Comment by harryhdt** [comment]
Hi @leonardodipace 
Thank you for your interest in svelte-simple-form! 🙌

This package is designed to simplify form submissions to APIs(Rest API) via `onSubmit` you can use native fetch or axios.
It doesn’t directly integrate with SvelteKit form actions out of the box. However, you can still use it effectively by create `+server.{js/ts}` on SvelteKit as rest api

**Comment by leonardodipace** [comment]
Thank you for the fast response!

Are you planning to support form actions at some point? I think it would be a great addition to the library because the Svelte ecosystem currently lacks a **_good_** form library that supports Svelte 5 like svelte-simple-form does!

**Comment by harryhdt** [comment]
I’m not planning to add support for SvelteKit form actions right now. The whole idea of this library is to keep things simple as reusable form management.
Adding SvelteKit actions could make it a bit too complex for what it’s meant to be.

I’ll leave this issue open in case someone in the community wants to jump in and make a PR to add support—it’d be awesome to see the library grow in that way without losing its simplicity! 😉

**Comment by harryhdt** [comment]
@leonardodipace 
I’ve tried integrating with SvelteKit form actions, and it works seamlessly. You can check out the example I created here: [Form Actions Example](https://github.com/harryhdt/svelte-simple-form/blob/main/example/form-actions.md).

Feel free to give it a try yourself and let me know if you encounter any issues or have suggestions for improvement! 😊

**Comment by leonardodipace** [comment]
@harryhdt this is awesome, thanks for providing an example so quickly!
I wasn't able to get it to work because I'm getting the following error: `Expected 1 arguments, but got 2`.

[It looks like](https://github.com/harryhdt/svelte-simple-form/blob/2309cf8967dba1aacf5d9a69d226fff67a9a8a3f/src/lib/form.svelte.ts#L240) the `enhance` function expects the form element as the only argument, which prevents from using the callback provided in the example

**Comment by harryhdt** [comment]
@leonardodipace 

😅 The enhance function in the example is indeed from SvelteKit.
Make sure you're importing it correctly as shown:
```
import { applyAction, enhance } from '$app/forms';
```
We use the native SvelteKit enhance function directly, so you can follow the example provided for seamless integration

**Comment by leonardodipace** [comment]
You're right, my bad - I was using the enhance function exposed by the library
